version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: matthewjamesbriggs/mxci:v001

    working_directory: ~/mx

    steps:
      - checkout

      - run:
          name: Cmake
          command: |
              [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ] && \
              cmake -DMX_BUILD_EXAMPLES=on -DMX_BUILD_TESTS=on -DMX_BUILD_CORE_TESTS=on . || \
              cmake -DMX_BUILD_EXAMPLES=on -DMX_BUILD_TESTS=on -DMX_BUILD_CORE_TESTS=off .
      
      - run:
          name: Build
          command: make

      - run:
          name: Run Examples
          command: ./MxRead && ./MxWrite

      - run:
          name: Test
          command: ./MxTest

      # - store_artifacts:
      #     path: /tmp/coverage/
